version: "3.2"
services:
  windows:
    image: dowerx/windows-qemu
    ports:
      - 5900:5900
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - /var/lib/libvirt/images/win10-basic.qcow2:/base.qcow2:ro
      - ./build/share:/share
    env_file:
      - .env.windows
  msbuild:
    image: dowerx/msbuild
    build: ./build
    volumes:
      - ./src:/src